# Generated by Django 5.0.1 on 2024-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/message_images/'),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
