# Generated by Django 5.0.1 on 2024-02-05 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='UserProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='pyMessage/static/profile_pictures/default.jpg', null=True, upload_to='pyMessage/static/profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
