# Generated by Django 5.0.1 on 2024-02-11 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuser_profile_picture_userprofilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profile_pictures/default.jpg', null=True, upload_to='static/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofilepic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
