# Generated by Django 5.0.1 on 2024-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofilepic_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
